meta_product_name: "SurfGo"
meta_title: "SurfGo - Trouvez les meilleures vagues !"
meta_description: "Cette application a été créée pour aider les jeunes surfeurs à mieux comprendre les informations météorologiques"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@Fatzy7"   # required for Twitter Cards